### ISSUE TITLE
회원가입 연락처 검증 

### ISSUE THREAD

**Issue by younggeun0** [younggeun0/1949#33]
![image](https://user-images.githubusercontent.com/34850791/53676764-5b1aaf00-3cea-11e9-8285-caf3ea6f6f00.png)

다음과 같을 때 에러 발생

![image](https://user-images.githubusercontent.com/34850791/53676770-6241bd00-3cea-11e9-9b89-3180e808802f.png)

**Comment by younggeun0** [comment]
![image](https://user-images.githubusercontent.com/34850791/53676779-9321f200-3cea-11e9-8e15-c0f9c55fbc2a.png)

추가로 로그 남길 땐 추가된 유저의 아이디가 기록에 남아야지.. 
너가 만든 저 LogTestSignUp 쓰지말고 user.util 패키지에 있는 UserLog클래스 사용하도록

**Comment by jeongmipark94** [comment]
int        부호 있는 정수    32 bits      -2147483648 ~ 2147483647
--------------------------------------------------------------------------------------
long       부호 있는 정수    64 bits      -9223372036854775808 ~ 9223372036854775807

parseint된 값이 int의 범위를 넘어가서 numberformat exception이 뜸
----------> long.parselong으로 처리함
