### ISSUE TITLE
기업 사진 등록 시 안내문구 필요

### ISSUE THREAD

**Issue by younggeun0** [younggeun0/1949#34]
![image](https://user-images.githubusercontent.com/34850791/53676791-b9e02880-3cea-11e9-9a3b-95880c97318e.png)

이미지 밑이나 옆에 "이미지란을 더블 클릭해서 이미지 등록이 가능합니다." 와 같은 안내문구 필요

**Comment by kimkunha** [comment]
이미지 하단에  안내문 작성 완료
