### ISSUE TITLE
회사정보 등록, 수정 시 설립년도 예외처리

### ISSUE THREAD

**Issue by younggeun0** [younggeun0/1949#35]
![image](https://user-images.githubusercontent.com/34850791/53677106-0d07aa80-3cee-11e9-8474-4de002c10751.png)

**Comment by younggeun0** [comment]
0000-00-00 식으로 입력해도 등록 가능하도록 처리

**Comment by kimkunha** [comment]
0000-00-00형식으로 예외처리 작성 완료
