### ISSUE TITLE
기업사용자 등록한 글에 지원자가 없을 시 상세지원현황 띄우지 말기

### ISSUE THREAD

**Issue by younggeun0** [younggeun0/1949#37]
![image](https://user-images.githubusercontent.com/34850791/53677162-e72ed580-3cee-11e9-8914-1011050566d6.png)

![image](https://user-images.githubusercontent.com/34850791/53677167-eb5af300-3cee-11e9-8bbe-50c07a6555d9.png)

읽을 글이 없는데 창이 뜨는 버그

**Comment by WABA82** [comment]
수정완료
