### ISSUE TITLE
관심 구직자 로그 보낼 때 어떤 유저를 관심 구직자로 등록했는지 메시지 수정

### ISSUE THREAD

**Issue by younggeun0** [younggeun0/1949#39]
![image](https://user-images.githubusercontent.com/34850791/53677205-b8fdc580-3cef-11e9-9c69-31ec115849ea.png)

**Comment by beans2** [comment]
기업사용자->관심구직자 // ee_num으로 구별해서 로그전송
일반사용자->관심구인글// er_num으로 구별해서 로그전송
