### ISSUE TITLE
엔터로 유저검증 수행

### ISSUE THREAD

**Issue by younggeun0** [younggeun0/1949#42]
![image](https://user-images.githubusercontent.com/34850791/53704832-54637780-3e63-11e9-95a6-7057c2b25dbb.png)

내용 입력 후 엔터로 유저검증 버튼을 누른 것과 동일한 처리

**Comment by younggeun0** [comment]
![image](https://user-images.githubusercontent.com/34850791/53704843-69400b00-3e63-11e9-8c43-25edce0dcf89.png)

위와 동일하게 엔터로 유저검증 처리

**Comment by younggeun0** [comment]
![image](https://user-images.githubusercontent.com/34850791/53704848-7ceb7180-3e63-11e9-9170-bbe7a4699fc1.png)

얘도

**Comment by hyewon0218** [comment]
작업끝!
