### ISSUE TITLE
no_ee_img.png 파일이 이상한것 같습니다.

### ISSUE THREAD

**Issue by beans2** [younggeun0/1949#56]
일반사용자에서 사진을 수정하면 사진이 뜨는경우도 있고 안뜨는 경우도 있습니다.
안뜨는 경우 에러메시지는 아래와 같습니다
![image](https://user-images.githubusercontent.com/45455322/53791869-c1633400-3f6d-11e9-9d24-b0be8f051943.png)

**Comment by younggeun0** [comment]
파일서버 닫혀있을 때 DB서버에만 값이 들어감
다른 이미지 넣어 해결
