### ISSUE TITLE
이미지 변경시 jpg가 대문자일때 이미지 못읽어옴

### ISSUE THREAD

**Issue by jeongmipark94** [younggeun0/1949#67]
![image](https://user-images.githubusercontent.com/45455409/54106520-d8949c80-4419-11e9-9b1b-8481bc502965.png)

xxx.jpg는 불러오는데 xxx.JPG 는 못불러오는 오류

**Comment by younggeun0** [comment]
이미지, 이력서 파일 확장자 대문자 시 못 읽는 문제, 대문자를 소문자로 바꾸는 예외처리 필요
