### ISSUE TITLE
로그 보내는 계정 형태 수정 

### ISSUE THREAD

**Issue by younggeun0** [younggeun0/1949#70]
![image](https://user-images.githubusercontent.com/34850791/54111228-b9503c00-4426-11e9-8876-449dd6d06780.png)

![image](https://user-images.githubusercontent.com/34850791/54111391-15b35b80-4427-11e9-832d-c4c238c86c96.png)

로그 수정 필요, 사용자 계정엔 "[]"를 붙이지 않음

**Comment by hyewon0218** [comment]
완료!
